### ISSUE TITLE
Auto translation of variable, question and concept labels into English 

### ISSUE THREAD

**Issue by jvjensen** [NordicHealthData/search-portal#42]
Auto translation of variable, question and concept labels into English at ingest transformation of xslt, for facet search.

**Comment by jvjensen** [comment]
Ingesting with call to translate.net takes ... well a long time with 120+ variables and the limit is 10000 translations a day - but whoo it is sweet.

Note:
Added enviroment variable: TRANSLATE_ON_INGEST with defaults to false

**Comment by borsna** [comment]
Nice work :+1:
