### ISSUE TITLE
view.blade.php errors on missing data. Undefined index: en.

### ISSUE THREAD

**Issue by nilsnh** [NordicHealthData/search-portal#44]
Received this error on certain study pages:

```
Undefined index: en (View: /var/www/sites/majken.snd.gu.se/html/nordic-health-demo/resources/views/study/view.blade.php)
```

Some pages where the error occurs:

_se.snd_

http://majken.snd.gu.se/nordic-health-demo/public/study/EXT0015
http://majken.snd.gu.se/nordic-health-demo/public/study/EXT0041

_dk.dda_

http://majken.snd.gu.se/nordic-health-demo/public/study/555
http://majken.snd.gu.se/nordic-health-demo/public/study/1667

This could be avoided by adding some integration tests maybe? Or possibly adding some schema validation on elasticsearch (I'm not that familiar with elasticsearch) so that the frontend won't have to handle as many different edge cases?

**Comment by jvjensen** [comment]
Problem: Elasticsearch is using the old index mappings.

Possible fix 1 or 2, the easiest is 1:
1: Delete the old index and ingest all json again.
2: do a remapping by hand, based on the mapping found i: https://github.com/NordicHealthData/search-portal/blob/master/resources/mapping/study.json

**Comment by borsna** [comment]
I am doing a new transformation right now and will do a ingest when its done.
Will check if this resolves the problem.

**Comment by borsna** [comment]
Har transformerat om alla dokument och ingestat dom, felet kvarstår dock så det när nog något som måste hanteras i renderingen.
